apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: py-calc-app
  template:
    metadata:
      labels:
        app: py-calc-app
    spec:
      containers:
      - name: py-calc-app
        image: yash5090/py-calc-app:latest
        ports:
        - containerPort: 5000
